---
default: &default
  corpid: <%= Rails.application.credentials.wechat_corpid %>
  corpsecret: <%= Rails.application.credentials.wechat_corp_secret %>
  agentid: <%= Rails.application.credentials.wechat_corp_agentid %>
  token: <%= Rails.application.credentials.wechat_corp_token %>
  encrypt_mode: true
  encoding_aes_key: <%= Rails.application.credentials.wechat_corp_encoding_aes_key %>
  access_token: "tmp/wechat_matlib_access_token"
  jsapi_ticket: "tmp/wechat_matlib_jsapi_ticket"

production:
  <<: *default

development:
  <<: *default
  trusted_domain_fullname: "http://your_dev.proxy.qqbrowser.cc"

test:
  <<: *default
